book/urls.py
from django.urls import path
from .views import bookDetailsView,BookBorrowView,BookReturnView

urlpatterns = [
    path('book_details/<int:pk>/',bookDetailsView.as_view(),name='book_details'),
    path('borrow/<int:id>/',BookBorrowView,name='book_borrow'),
    path("return/<int:id>/",BookReturnView,name='return'),
]

library_management_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('librarians/', include('librarians.urls')),
    path('transactions/', include('transactions.urls')),
    path('book/', include('book.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class bookCategory(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,unique=True,null=True, blank=True, )

    def __str__(self):
        return f'{self.name}'


class BookModel(models.Model):
    book_name = models.CharField(max_length=255)
    category = models.ForeignKey(bookCategory, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField()
    image = models.ImageField(upload_to='upload/book_images/', blank= True, null= True)
    book_quantity=models.IntegerField()
    borrow_book_quantity = models.IntegerField(default=0)
    borrow_price = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    
    def __str__(self):
        return f'{self.book_name}'
    

class BorrowModel(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)
    book = models.ForeignKey(BookModel,on_delete=models.CASCADE,null=True, blank=True)
    status=models.BooleanField(default=False)
    borrow_date = models.DateField(auto_now=True)
    # balance_after_transaction = models.DecimalField(default=0, max_digits=12, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f'{self.book} borrowed by {self.user}'
    
class ReturnModel(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)
    book = models.ForeignKey(BookModel,on_delete=models.CASCADE,null=True, blank=True)
    status=models.BooleanField(default=False)
    return_date = models.DateField(auto_now=True)
    
    def __str__(self):
        return f'{self.book} returned by {self.user}'

class CommentModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    book = models.ForeignKey(BookModel, on_delete=models.CASCADE, related_name='comment')
    name = models.CharField(max_length=30)
    comment_body = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Comments by {self.name}'

book/forms.py
from book.models import bookCategory, BookModel, BorrowModel, CommentModel
from django import forms

class CategoryForm(forms.ModelForm):
    class Meta:
        model = bookCategory
        fields = '__all__'


class BookForm(forms.ModelForm):
    class Meta:
        model = BookModel
        fields = ['book_name', 'category', 'description', 'image', 'book_quantity', 'borrow_price']

    
class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        fields = ['comment_body']

book/views.py
from django.views import View
from django.shortcuts import render,redirect, get_object_or_404
from .models import BookModel, CommentModel, BorrowModel, ReturnModel
from librarians.models import UserProfile
from .forms import CommentForm
from django.views.generic import DetailView
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.contrib import messages
# Create your views here.
    
class bookDetailsView(DetailView):
    model = BookModel
    template_name = "book_details.html"
    pk_url_kwarg = "pk"
    context_object_name = "book_details"

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(data=self.request.POST)
        requested_book = self.get_object()
        print(requested_book)
        user = request.user
        
        if not BorrowModel.objects.filter(user=user, book=requested_book, status=True).exists():
            messages.error(request, "You can review it if you must have borrowed this book before")
            return self.get(request, *args, **kwargs)

        if comment_form.is_valid():
            print("inside")
            try:
                comment = comment_form.save(commit=False)
                comment.user = request.user
                comment.book = requested_book
                comment.save()
                messages.success(request, "Your review has been submitted successfully.")
            except IntegrityError:
                messages.error(request, "There was an error submitting your review. Please try again.")
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = self.get_object()
        if self.request.user.is_authenticated:
            user = self.request.user
            flag = BorrowModel.objects.filter(
                user=user,
                book=book,
                status=True,
            ).exists()
            context["flag"] = flag
        comments = book.comment.all()
        context["comments"] = comments
        context["CommentForm"] = CommentForm()
        return context
    
    
def sendOrderemail(user, amount, book, subject):
    message = render_to_string(
        "borrow_email.html",
        {
            "user": user,
            "book": book,
            "amount": amount,
            "operation": subject,
        },
    )
    send_email = EmailMultiAlternatives(subject=subject, body="", to=[user.email])
    send_email.attach_alternative(message, "text/html")
    send_email.send()
    
def sendReturnemail(user, amount, book, subject):
    message = render_to_string(
        "return_email.html",
        {
            "user": user,
            "book": book,
            "amount": amount,
            "operation": subject,
        },
    )
    send_email = EmailMultiAlternatives(subject=subject, body="", to=[user.email])
    send_email.attach_alternative(message, "text/html")
    send_email.send()


def BookBorrowView(request, id):
    print(id)
    requested_book = BookModel.objects.get(id=id)
    print(requested_book)
    requested_user = UserProfile.objects.get(user=request.user)
    if requested_user.balance > requested_book.borrow_price:
        if  requested_book.book_quantity >= 0:
            requested_book.book_quantity -= 1
            requested_book.borrow_book_quantity += 1 
            requested_book.save()
            requested_user.balance -= requested_book.borrow_price
            sendOrderemail(
                request.user, requested_book.borrow_price, requested_book.book_name, "Borrow"
            )
            requested_user.save()
            borrow_object = BorrowModel.objects.create(
                user=request.user,
                book=requested_book,
                status=True,
            )
            borrow_object.save()
        else:
            messages.error(request, "Sorry, Out Of Stock!")
        return redirect('book_details', pk=id)
    else:
        messages.error(request, "You don't have enough balance to borrow this book.")
    return redirect('book_details', pk=id)


def BookReturnView(request, id):
    if request.method == "POST":
        book_id = id
        print(book_id)

        requested_book = get_object_or_404(BookModel, id=book_id)
        requested_user_profile = get_object_or_404(UserProfile, user=request.user)
        
        borrow_record = BorrowModel.objects.filter(user=request.user, book=requested_book, status=True).first()
        
        if borrow_record:
            requested_book.book_quantity += 1
            requested_book.borrow_book_quantity -= 1
            requested_book.save()
            
            requested_user_profile.balance += requested_book.borrow_price
            requested_user_profile.save()
            
            borrow_record.delete()
            
            ReturnModel.objects.create(
                user=request.user,
                book=requested_book,
                status=True,
            )
            
            sendReturnemail(
                request.user, requested_book.borrow_price, requested_book.book_name, "Return"
            )
            messages.success(request, f'You have successfully returned "{requested_book.book_name}".')
        else:
            messages.error(request, "You haven't borrowed this book, so you cannot return it.")
        return redirect("book_details", pk=id)

book/templates/book_details.html
{% extends 'base.html' %}
{% block title %}
<title>Library Management System</title>
{% endblock %}

{% block body %}
{% include 'messages.html'%}
<div class="flex flex-col lg:flex-row lg:space-x-6 p-5">
    <div class="lg:w-1/2 w-full flex justify-center mb-6 lg:mb-0">
        <img src="{{book_details.image.url}}" alt="" class="w-80 h-auto object-cover">
    </div>

    <div class="lg:w-1/2 w-full p-5">
        <h2 class="text-2xl font-bold mb-2">Name: {{book_details.book_name}}</h2>
        <hr class="my-4">
        <h5 class="text-lg mb-4">Description: {{book_details.description}}</h5>
        <hr class="my-4">
        <h5 class="text-lg mb-4">Category: 
            <button class="bg-green-500 text-white py-2 px-4 rounded" disabled>
                <b>{{book_details.category}}</b>
            </button>
        </h5>
        <hr class="my-4">
        <h5 class="text-dark-600 text-lg mb-4">Borrowed Book Quantity: {{ book_details.borrow_book_quantity }}</h5>
        {% if book_details.book_quantity >= 1 %}
        <h5 class="text-dark-600 text-lg mb-4">Book Quantity: {{book_details.book_quantity}}</h5>
        {% else %}
        <h5 class="text-red-600 text-lg mb-4">Out of Stock</h6>
        {% endif %}
        <h5 class="text-red-600 text-lg mb-4">Borrow Price: {{book_details.borrow_price}}$</h5>
        <hr class="my-4">
        {% if user.is_authenticated %}
        <div class="mt-4 flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
          <form method="post" action="{% url 'return' book_details.id %}" class="flex-1">
              {% csrf_token %}
              <button class="w-full bg-yellow-600 hover:bg-yellow-700 text-white font-bold py-3 rounded-md shadow-md transition duration-300 ease-in-out">
                  Return
              </button>
          </form>


          <form method="post" action="{% url 'book_borrow' book_details.id %}" class="flex-1">
              {% csrf_token %}
              <button type="submit" class="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 rounded-md shadow-md transition duration-300 ease-in-out">
                  Borrow
              </button>
          </form>
        </div>
        {% endif %}
    </div>
</div>

<!-- Show comments -->
<div class="w-3/4 mx-auto mt-8">
    <div class="bg-white shadow-lg rounded-lg p-5">
      <h4 class="text-xl font-semibold mb-4">Total Reviews: {{comments | length}}</h4>
      {% for cmnt in comments %}
      <hr class="my-4">
      <div class="p-4 border border-gray-200 rounded-lg">
        <p class="font-semibold"><span class="text-gray-500 text-sm">{{cmnt.date}}</span></p>
        <p class="mt-2">{{cmnt.comment_body}}</p>
      </div>
      <hr class="my-4">
      {% endfor %}
    </div>
</div>

<!-- Comment form -->
{% if user.is_authenticated %}
{% if flag %}
<div class="w-3/4 mx-auto mt-8">
  <h4 class="text-xl font-semibold mb-4">Add your Review...</h4>
  <div class="bg-white shadow-lg rounded-lg p-5">
    <form method="post">
      {% csrf_token %}
      <div class="mb-4">
        <label for="id_comment_body" class="block text-gray-700 text-sm font-bold mb-2">Comment:</label>
        <textarea id="id_comment_body" name="comment_body" rows="4" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required></textarea>
      </div>
      <button type="submit" class="bg-green-500 text-white py-2 px-4 rounded hover:bg-green-600 mt-4">
        Submit
      </button>
    </form>
  </div>
</div>
{% else %}
<div class="bg-white">
<p class="text-center" style="color: red; font-weight: bold; margin-top: 20px;">
  You must borrow this book before you can submit a review.
</p>
</div>
{% endif %}
{% endif %}
{% endblock %}

book/templates/borrow_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>

<p>{{book}} is borrowed successfully! {{amount}}$ has been deducted from your total balance.</p>

<p>Thanks for connected with us.</p>
<p>BookHub Team</p>

book/templates/return_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>

<p>{{book}} is returned successfully! {{amount}}$ has been added to your balance.</p>

<p>Thanks for connected with us.</p>
<p>BookHub Team</p>